# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbd < Formula
  desc "TUI for beads (bd) issue tracker"
  homepage "https://github.com/kostine/kbd"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_darwin_amd64.tar.gz"
      sha256 "1c28f01e1a0b49a5960b797c99e214567d529d12b70cd361774590d24c325483"

      define_method(:install) do
        bin.install "kbd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_darwin_arm64.tar.gz"
      sha256 "2fbc5cc13a4a7e525e35d2b994c8ac0d653a6f0007ba2dc458409d2507b9b976"

      define_method(:install) do
        bin.install "kbd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_linux_amd64.tar.gz"
      sha256 "d544a0211c741049b16bd1108bb32d47998c9bdc8e719617212d05a62cc92156"
      define_method(:install) do
        bin.install "kbd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_linux_arm64.tar.gz"
      sha256 "ee9dc7ce21101c8c5403cf8c7dfaabd6cc82cda780a7cb9c8e679d86f9b2f008"
      define_method(:install) do
        bin.install "kbd"
      end
    end
  end

  test do
    system "#{bin}/kbd", "--help"
  end
end
