# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbd < Formula
  desc "TUI for beads (bd) issue tracker"
  homepage "https://github.com/kostine/kbd"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_darwin_amd64.tar.gz"
      sha256 "29b8384c3b8874616cbfaa072a45ec71d48b9706a0b4715b022bd42c485cc817"

      define_method(:install) do
        bin.install "kbd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_darwin_arm64.tar.gz"
      sha256 "d80016f720cad1a0a2a4220b26679434f2cbb08aaa51900ae528b9069f76052f"

      define_method(:install) do
        bin.install "kbd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_linux_amd64.tar.gz"
      sha256 "be9e9c107201671955583cfa85eeb66e60a9304d3f276c5262565446f4673e1f"
      define_method(:install) do
        bin.install "kbd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_linux_arm64.tar.gz"
      sha256 "17a8ebe887f1b288bae758736c28ac8380181c9e27fccae489b8984a6713769c"
      define_method(:install) do
        bin.install "kbd"
      end
    end
  end

  test do
    system "#{bin}/kbd", "--help"
  end
end
