# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbd < Formula
  desc "TUI for beads (bd) issue tracker"
  homepage "https://github.com/kostine/kbd"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_darwin_amd64.tar.gz"
      sha256 "377dbb6fd81c034bd7046d520d0ce5102c57752a50beb8427306be5fba9ab899"

      define_method(:install) do
        bin.install "kbd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_darwin_arm64.tar.gz"
      sha256 "4100a7bffad26fba3bc767c8968c7c22a98cbeb316b9c6d211632989e631a5ab"

      define_method(:install) do
        bin.install "kbd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_linux_amd64.tar.gz"
      sha256 "10d853dce8f86ba2b5e2ed1e5afc9cb337c0105aed12fb379209adc09b43ed6c"
      define_method(:install) do
        bin.install "kbd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kostine/kbd/releases/download/v0.1.0/kbd_0.1.0_linux_arm64.tar.gz"
      sha256 "02f8e91e5e9c613e80b7d8ff9c3a9aea3b205edbbe8a06bc2e47cddd429bcf67"
      define_method(:install) do
        bin.install "kbd"
      end
    end
  end

  test do
    system "#{bin}/kbd", "--help"
  end
end
